"""add users and user relations

Revision ID: 222467914f28
Revises: 76284bc22fc4
Create Date: 2026-09-26 03:52:42.487625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222467914f28'
down_revision: Union[str, Sequence[str], None] = '76284bc22fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('edit_mode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_user_id')
    )
    op.create_table('user_olympiads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('olympiad_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'olympiad_id')
    )
    op.create_table('user_selected_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level')
    )
    op.create_table('user_subjects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subjects')
    op.drop_table('user_selected_levels')
    op.drop_table('user_olympiads')
    op.drop_table('users')
    # ### end Alembic commands ###
