"""add olympiad relations and stages

Revision ID: d09d31344980
Revises: aecef265295e
Create Date: 2026-09-26 02:10:43.693679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09d31344980'
down_revision: Union[str, Sequence[str], None] = 'aecef265295e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympiad_grades',
    sa.Column('olympiad_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('olympiad_id', 'grade')
    )
    op.create_table('olympiad_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('olympiad_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olympiad_subjects',
    sa.Column('olympiad_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('olympiad_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olympiad_subjects')
    op.drop_table('olympiad_stages')
    op.drop_table('olympiad_grades')
    # ### end Alembic commands ###
